default_stages: [pre-commit]
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0 #v4.0.1
      hooks:
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
  -   repo: https://github.com/psf/black
      rev: 25.1.0
      hooks:
        -   id: black
            exclude: ^.github/
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.17.0 #0.910
      hooks:
        -   id: mypy
            additional_dependencies: [types-requests]
            exclude: ^.github/
  -   repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
        - id: isort
          args: [--profile, black, --filter-files]
          exclude: ^.github/
  -   repo: https://github.com/pycqa/flake8
      rev: 7.3.0 #4.0.1
      hooks:
        -   id: flake8
            additional_dependencies: [flake8-bugbear]
            exclude: ^.github/
  -   repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0 #6.1.1
      hooks:
        -   id: pydocstyle
            files: "^inference_service/.*\\.py"
            additional_dependencies: [toml]
            exclude: ^.github/
  -   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
      rev: v1.1.2 #v1.1.1
      hooks:
        -   id: markdown-toc
            files: ^README\.md$
            args: [-i, --bullets, "*"]
  -   repo: https://github.com/DavidAnson/markdownlint-cli2
      rev: v0.18.1 #v0.2.0
      hooks:
        -   id: markdownlint-cli2
            exclude: ^.github/
