repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 38b88246ccc552bffaaf54259d064beeee434539 #v4.0.1
      hooks:
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
  -   repo: https://github.com/psf/black
      rev: e3000ace2fd1fcb1c181bb7a8285f1f976bcbdc7 #21.7b0
      hooks:
        -   id: black
            exclude: ^.github/
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 44afb68a9695d04030edc5cdc5a4fc4f17e4f9e2 #0.910
      hooks:
        -   id: mypy
            additional_dependencies: [types-requests]
            exclude: ^.github/
  -   repo: https://github.com/pycqa/isort
      rev: fd5ba70665a37ec301a1f714ed09336048b3be63 #5.9.3
      hooks:
        - id: isort
          args: [--profile, black, --filter-files]
          exclude: ^.github/
  -   repo: https://github.com/pycqa/flake8
      rev: 82b698e09996cdde5d473e234681d8380810d7a2 #4.0.1
      hooks:
        -   id: flake8
            additional_dependencies: [flake8-bugbear]
            exclude: ^.github/
  -   repo: https://github.com/pycqa/pydocstyle
      rev: faeaa735d5c9387ab2f02c5bf9d4f07d0e7b6841 #6.1.1
      hooks:
        -   id: pydocstyle
            files: "^inference_service/.*\\.py"
            additional_dependencies: [toml]
            exclude: ^.github/
  -   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
      rev: b234899b5db911d0e5482deffcf4e6364ad349d0 #v1.1.1
      hooks:
        -   id: markdown-toc
            files: ^README\.md$
            args: [-i, --bullets, "*"]
  -   repo: https://github.com/DavidAnson/markdownlint-cli2
      rev: 7f2cb1a915520a6139f09749836379ff57819380 #v0.2.0
      hooks:
        -   id: markdownlint-cli2
            exclude: ^.github/