# .readthedocs.yaml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools: {python: "3.10"}
  jobs:
    pre_create_environment:
      - python -m pip install poetry
      - python -m poetry config virtualenvs.in-project true
      - python -m poetry install
      - source ./.venv/bin/activate  # Activate the virtual environment
    post_install:
      - poetry install

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
