"""Auto-generated by BlueCastAI."""

import numpy as np
import pandas as pd

# --- Feature Engineering ---
cols_to_drop = [col for col in ['spectral_type', 'galaxy_population'] if col in df.columns]
if cols_to_drop:
    df = df.drop(columns=cols_to_drop)

if all(c in df.columns for c in ['u', 'g', 'r', 'i', 'z']):
    df['u_g'] = df['u'] - df['g']
    df['g_r'] = df['g'] - df['r']
    df['r_i'] = df['r'] - df['i']
    df['i_z'] = df['i'] - df['z']

if all(c in df.columns for c in ['u', 'g', 'r', 'i', 'z']):
    df['u_r'] = df['u'] - df['r']
    df['u_i'] = df['u'] - df['i']
    df['u_z'] = df['u'] - df['z']
    df['g_i'] = df['g'] - df['i']
    df['g_z'] = df['g'] - df['z']
    df['r_z'] = df['r'] - df['z']

bands = ['u', 'g', 'r', 'i', 'z']
if 'redshift' in df.columns:
    for b in bands:
        if b in df.columns:
            df[f'redshift_mul_{b}'] = df['redshift'] * df[b]

from bluecast.preprocessing.feature_creation import add_pca_features
bands = ['u', 'g', 'r', 'i', 'z']
existing_bands = [b for b in bands if b in df.columns]
if len(existing_bands) == 5:
    df = add_pca_features(df, cols=existing_bands, n_components=3, state=state, is_fit=is_fit)

if 'alpha' in df.columns and 'delta' in df.columns:
    alpha_rad = np.radians(df['alpha'])
    delta_rad = np.radians(df['delta'])
    df['coord_x'] = np.cos(alpha_rad) * np.cos(delta_rad)
    df['coord_y'] = np.sin(alpha_rad) * np.cos(delta_rad)
    df['coord_z'] = np.sin(delta_rad)

from bluecast.preprocessing.feature_creation import add_polynomial_features
cols = [c for c in ['u', 'g', 'r', 'i', 'z', 'redshift'] if c in df.columns]
if len(cols) > 0:
    df = add_polynomial_features(df, cols=cols, degree=2)

df = df.fillna(0)

df['u_g_color'] = df['u'] - df['g']
df['g_r_color'] = df['g'] - df['r']
df['r_i_color'] = df['r'] - df['i']
df['i_z_color'] = df['i'] - df['z']
