"""Auto-generated by BlueCastAI."""

import numpy as np
import pandas as pd

# --- Feature Engineering ---
import numpy as np

df['x5_is_missing'] = (df['x5'] == 999.0).astype(int)
df['x5_temp'] = df['x5'].replace(999.0, np.nan)

if is_fit:
    state['x5_median'] = df['x5_temp'].median()

df['x5'] = df['x5_temp'].fillna(state['x5_median'])
df = df.drop(columns=['x5_temp'])

df['x4_x9_diff'] = df['x4'] - df['x9']
df['x4_x9_ratio'] = df['x4'] / (df['x9'] + 1e-5)

from bluecast.preprocessing.feature_creation import StateAwareGroupbyAggregator

if 'city_agg' not in state:
    state['city_agg'] = StateAwareGroupbyAggregator(
        groupby_cols=['City'], 
        agg_cols=['x4', 'x5', 'x9', 'x8', 'x10', 'x11'], 
        aggregations=['mean', 'std']
    )

if is_fit:
    df = state['city_agg'].fit_transform(df)
else:
    df = state['city_agg'].transform(df)

from bluecast.preprocessing.feature_creation import add_binned_features

df = add_binned_features(df, cols=['x6', 'x7'], num_bins=5, state=state, is_fit=is_fit)

from bluecast.preprocessing.feature_creation import add_pca_features

df = add_pca_features(df, cols=['x1', 'x2', 'x8', 'x10', 'x11'], n_components=3, state=state, is_fit=is_fit)

from bluecast.preprocessing.feature_creation import add_polynomial_features

df = add_polynomial_features(df, cols=['x4', 'x9'], degree=2)

df['x5_is_missing'] = (df['x5'] == 999.0).astype(int)
df.loc[df['x5'] == 999.0, 'x5'] = np.nan

from bluecast.preprocessing.feature_creation import StateAwareGroupbyAggregator

if 'city_agg' not in state:
    state['city_agg'] = StateAwareGroupbyAggregator(
        groupby_cols=['City'], 
        agg_cols=['x4', 'x9'], 
        aggregations=['mean', 'std']
    )

if is_fit:
    df = state['city_agg'].fit_transform(df)
else:
    df = state['city_agg'].transform(df)
