"""Auto-generated by BlueCastAI."""

import numpy as np
import pandas as pd

# --- Feature Engineering ---
df['x5_is_missing'] = (df['x5'] == 999.0).astype(int)
df['x5'] = df['x5'].replace(999.0, 0.0)

from bluecast.preprocessing.feature_creation import StateAwareGroupbyAggregator

if 'city_agg' not in state:
    state['city_agg'] = StateAwareGroupbyAggregator(
        groupby_cols=['City'], 
        agg_cols=['x4', 'x5', 'x6', 'x7'], 
        aggregations=['mean', 'std']
    )

if is_fit:
    df = state['city_agg'].fit_transform(df)
else:
    df = state['city_agg'].transform(df)

df['x4_div_x5'] = df['x4'] / (df['x5'].clip(lower=1e-5))

from bluecast.preprocessing.feature_creation import add_pca_features

pca_cols = ['x1', 'x2', 'x4', 'x5', 'x6', 'x7', 'x8', 'x10', 'x11']

if 'pca_scaler_mean' not in state:
    state['pca_scaler_mean'] = df[pca_cols].mean()
    state['pca_scaler_std'] = df[pca_cols].std().replace(0, 1)

temp_df = df.copy()
for col in pca_cols:
    temp_df[col] = (temp_df[col] - state['pca_scaler_mean'][col]) / state['pca_scaler_std'][col]

temp_df = add_pca_features(temp_df, cols=pca_cols, n_components=3, state=state, is_fit=is_fit)

new_cols = [c for c in temp_df.columns if c not in df.columns]
for c in new_cols:
    df[c] = temp_df[c]

from bluecast.preprocessing.feature_creation import add_binned_features
df = add_binned_features(df, cols=['x4', 'x6', 'x7'], num_bins=5, state=state, is_fit=is_fit)

from bluecast.preprocessing.feature_creation import add_polynomial_features
df = add_polynomial_features(df, cols=['x4', 'x5'], degree=2)

df['x5_is_missing'] = (df['x5'] == 999.0).astype(int)
df['x5'] = df['x5'].replace(999.0, np.nan)

from bluecast.preprocessing.feature_creation import StateAwareGroupbyAggregator

if 'city_agg' not in state:
    state['city_agg'] = StateAwareGroupbyAggregator(
        groupby_cols=['City'], 
        agg_cols=['x4', 'x5'], 
        aggregations=['mean', 'std']
    )

if is_fit:
    df = state['city_agg'].fit_transform(df)
else:
    df = state['city_agg'].transform(df)
