"""Exploratory Data Analysis utilities for BlueCast."""

from bluecast.eda.analyse import (
    bi_variate_plots,
    correlation_heatmap,
    correlation_to_target,
    mutual_info_to_target,
    plot_against_target_for_regression,
    plot_andrews_curve,
    plot_benfords_law,
    plot_category_frequency,
    plot_classification_target_distribution_within_categories,
    plot_count_pair,
    plot_count_pairs,
    plot_distribution_by_time,
    plot_distribution_pairs,
    plot_ecdf,
    plot_error_distributions,
    plot_missing_values_matrix,
    plot_null_percentage,
    plot_pca,
    plot_pca_biplot,
    plot_pca_cumulative_variance,
    plot_pie_chart,
    plot_theil_u_heatmap,
    plot_tsne,
    univariate_plots,
)
from bluecast.eda.dashboard import create_eda_dashboard
from bluecast.eda.data_leakage_checks import (
    detect_categorical_leakage,
    detect_leakage_via_correlation,
)

__all__ = [
    "bi_variate_plots",
    "correlation_heatmap",
    "correlation_to_target",
    "create_eda_dashboard",
    "detect_categorical_leakage",
    "detect_leakage_via_correlation",
    "mutual_info_to_target",
    "plot_against_target_for_regression",
    "plot_andrews_curve",
    "plot_benfords_law",
    "plot_category_frequency",
    "plot_classification_target_distribution_within_categories",
    "plot_count_pair",
    "plot_count_pairs",
    "plot_distribution_by_time",
    "plot_distribution_pairs",
    "plot_ecdf",
    "plot_error_distributions",
    "plot_missing_values_matrix",
    "plot_null_percentage",
    "plot_pca",
    "plot_pca_biplot",
    "plot_pca_cumulative_variance",
    "plot_pie_chart",
    "plot_theil_u_heatmap",
    "plot_tsne",
    "univariate_plots",
]
