name: Example workflow for Codecov
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.10'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install poetry
        run: |
            python -m pip install poetry
      - name: Configure poetry
        run: |
            python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
            python -m poetry install
      - name: Generate coverage report
        run: |
          source ./.venv/bin/activate  # Activate the virtual environment
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: List installed packages
        run: |
          python -m poetry lock
          python -m poetry show --tree
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: |
            ./coverage.xml
          flags: pytest
          name: codecov-umbrella
          verbose: true
